@extends('layouts.app', [
  'pageTitle' => 'Voucher List',
  'iconSource' => 'images/coldoc.png',
  'pageSubTitle' => 'Master Voucher List Management'
  ])


@section("MainContent")


  <div class="container">
    <div class="v-tableDiv">
      
      <table class="table" id="table">
      <thead>
        <tr>
          <th >Serial No.</th>
          <th >Voucher Name</th>
          <th>Value</th>
          <th >Expiry Date</th>
          <th >Generated on</th>
          <th >Generated By</th>
          <th>Status</th>
          <th>Download</th>

        </tr>
      </thead>
      <tbody>

        @foreach($vouchers as $voucher)

          @php

            $num = $voucher->id;
            $str_length = 10;
            $serial = substr("000000000{$num}", -$str_length);
          @endphp
 
          <tr>
            <td>{{ $serial }}</td>
            <td class="text-left">{{ $voucher->voucher_name }}</td>
            <td class="text-center">{{ 'D'.' '. $voucher->value }}</td>
            <td class="text-center">{{ $voucher->expiry_date }}</td>
            <td class="text-center">{{ date('Y-m-d', strtotime($voucher->created_at)) }}</td>
            <td class="text-center">{{ $voucher->created_by }}</td>
            
            @if($voucher->status == 'Valid')

            <td class="text-center"><a href="/change-status?id=<?php echo $voucher->id; ?>" class="btn btn-success">{{ $voucher->status }}</a></td>

            @else  

            <td class="text-center">{{ $voucher->status }}</td>

            @endif

            <td class="text-center">
              <div onclick="location.href='/individual?id=<?php echo $voucher->id; ?>';" style="cursor: pointer;">
                <img src="images/download.png" width="20" height="20">
              </div>
            </td>
            </tr>
        @endforeach

        </tbody>
      </table>
      </div>
    </div><!-- .container -->


    @section('extraScripts')
      <script>
        $(document).ready( function () {
          $('#table').DataTable();
        });
      </script>
    @endsection

@endsection


